# Generated by Django 3.2.5 on 2022-11-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
